FROM centos:7

MAINTAINER David Yang <yangyulin629@163.com>

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]

RUN yum -y install gcc libxml2-devel wget autoconf make

RUN wget http://cn2.php.net/distributions/php-7.2.4.tar.gz \
  && tar -zxvf php-7.2.4.tar.gz \
  && cd php-7.2.4 \
  && ./configure --disable-cli\
  && make \
  && make install

WORKDIR /var/www

COPY php-cgi.service /etc/systemd/system/php-cgi.service

RUN systemctl enable php-cgi.service

CMD ["/usr/sbin/init"]

EXPOSE 9000