FROM centos:7

MAINTAINER David Yang <yangyulin629@163.com>

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]

RUN yum -y install gcc libxml2-devel wget autoconf make

RUN wget http://us2.php.net/distributions/php-5.6.35.tar.gz

RUN tar -zxvf php-5.6.35.tar.gz \
  && cd php-5.6.35 \
  && ./configure --disable-cgi\
  && make \
  && make install \
  && cd .. \
  && rm -rf php-5.6.35 php-5.6.35.tar.gz

RUN wget https://pecl.php.net/get/vld-0.14.0.tgz

RUN tar -zxvf vld-0.14.0.tgz \
  && cd vld-0.14.0 && phpize \
  && ./configure --with-php-config=/usr/local/bin/php-config --enable-vld \
  && make \
  && make install \
  && cd .. \
  && rm -rf vld-0.14.0 vld-0.14.0.tgz

WORKDIR /var/www

CMD ["/usr/sbin/init"]
